caijinpeng
v4.3.12-with-kafka

diff --git a/build b/build
--- a/build
+++ b/build
@@ -1,48 +1,21 @@
 #!/usr/bin/env bash
 
 # This script helps to build release artifacts.
-# arg1: profile, e.g. emqx | emqx-enterprise
-# arg2: artifact, e.g. rel | relup | tgz | pkg
+# arg1: profile, e.g. emqx | emqx-edge | emqx-pkg | emqx-edge-pkg
+# arg2: artifact, e.g. rel | relup | zip | pkg
 
+if [[ -n "$DEBUG" ]]; then
+    set -x
+fi
 set -euo pipefail
 
-[ "${DEBUG:-0}" -eq 1 ] && set -x
-
-PROFILE_ARG="$1"
+PROFILE="$1"
 ARTIFACT="$2"
-
-is_enterprise() {
-    case "$1" in
-        *enterprise*)
-            echo 'yes'
-            ;;
-        *)
-            echo 'no'
-            ;;
-    esac
-}
-PROFILE_ENV="${PROFILE:-${PROFILE_ARG}}"
-case "$(is_enterprise "$PROFILE_ARG"),$(is_enterprise "$PROFILE_ENV")" in
-    'yes,yes')
-        true
-        ;;
-    'no,no')
-        true
-        ;;
-    *)
-        echo "PROFILE env var is set to '$PROFILE_ENV', but '$0' arg1 is '$PROFILE_ARG'"
-        exit 1
-        ;;
-esac
-
-# make sure PROFILE is exported, it is needed by rebar.config.erl
-PROFILE=$PROFILE_ARG
-export PROFILE
 
 # ensure dir
 cd -P -- "$(dirname -- "${BASH_SOURCE[0]}")"
 
-PKG_VSN="${PKG_VSN:-$(./pkg-vsn.sh "$PROFILE")}"
+PKG_VSN="${PKG_VSN:-$(./pkg-vsn.sh)}"
 export PKG_VSN
 
 SYSTEM="$(./scripts/get-distro.sh)"
@@ -56,7 +29,7 @@ case "$ARCH" in
         ARCH='arm64'
         ;;
     arm*)
-        ARCH='arm64'
+        ARCH=arm
         ;;
 esac
 export ARCH
@@ -75,112 +48,39 @@ if [ "$(uname -s)" = 'Linux' ]; then
     esac
 fi
 
-if [ "${SYSTEM}" = 'windows' ]; then
-    # windows does not like the find
-    FIND="/usr/bin/find"
-    TAR="/usr/bin/tar"
-    export BUILD_WITHOUT_ROCKSDB="on"
-else
-    FIND='find'
-    TAR='tar'
-fi
-
 log() {
     local msg="$1"
     # rebar3 prints ===>, so we print ===<
     echo "===< $msg"
 }
 
-make_docs() {
-    local libs_dir1 libs_dir2 libs_dir3 docdir
-    libs_dir1="$("$FIND" "_build/$PROFILE/lib/" -maxdepth 2 -name ebin -type d)"
-    if [ -d "_build/default/lib/" ]; then
-        libs_dir2="$("$FIND" "_build/default/lib/" -maxdepth 2 -name ebin -type d)"
-    else
-        libs_dir2=''
-    fi
-    if [ -d "_build/$PROFILE/checkouts" ]; then
-        libs_dir3="$("$FIND" "_build/$PROFILE/checkouts/" -maxdepth 2 -name ebin -type d 2>/dev/null || true)"
-    else
-        libs_dir3=''
-    fi
-    case "$(is_enterprise "$PROFILE")" in
-        'yes')
-            SCHEMA_MODULE='emqx_ee_conf_schema'
-            ;;
-        'no')
-            SCHEMA_MODULE='emqx_conf_schema'
-            ;;
-    esac
-    docdir="_build/docgen/$PROFILE"
-    mkdir -p "$docdir"
-    # shellcheck disable=SC2086
-    erl -noshell -pa $libs_dir1 $libs_dir2 $libs_dir3 -eval \
-        "ok = emqx_conf:dump_schema('$docdir', $SCHEMA_MODULE), \
-         halt(0)."
-}
-
-assert_no_compile_time_only_deps() {
-    :
-}
-
-just_compile() {
-    ./scripts/pre-compile.sh "$PROFILE"
-    # make_elixir_rel always create rebar.lock
-    # delete it to make git clone + checkout work because we use shallow close for rebar deps
-    rm -f rebar.lock
-    # compile all beams
-    ./rebar3 as "$PROFILE" compile
-    make_docs
-}
-
 make_rel() {
-    local release_or_tar="${1}"
-    just_compile
-    # now assemble the release tar
-    ./rebar3 as "$PROFILE" "$release_or_tar"
-    assert_no_compile_time_only_deps
+    # shellcheck disable=SC1010
+    ./rebar3 as "$PROFILE" do release,tar
 }
 
-make_elixir_rel() {
-  ./scripts/pre-compile.sh "$PROFILE"
-  export_elixir_release_vars "$PROFILE"
-  # for some reason, this has to be run outside "do"...
-  mix local.rebar --if-missing --force
-  # shellcheck disable=SC1010
-  mix do local.hex --if-missing --force, \
-      local.rebar rebar3 "${PWD}/rebar3" --if-missing --force, \
-      deps.get
-  mix release --overwrite
-  assert_no_compile_time_only_deps
-}
-
-## extract previous version .tar.gz files to _build/$PROFILE/rel/emqx before making relup
+## unzip previous version .zip files to _build/$PROFILE/rel/emqx/releases before making relup
 make_relup() {
-    local rel_dir="_build/$PROFILE/rel/emqx"
-    local name_pattern
-    name_pattern="${PROFILE}-$(./pkg-vsn.sh "$PROFILE" --vsn_matcher --long)"
+    local lib_dir="_build/$PROFILE/rel/emqx/lib"
+    local releases_dir="_build/$PROFILE/rel/emqx/releases"
+    mkdir -p "$lib_dir" "$releases_dir"
     local releases=()
-    mkdir -p _upgrade_base
-    while read -r tgzfile ; do
-        local base_vsn
-        base_vsn="$(echo "$tgzfile" | grep -oE "[0-9]+\.[0-9]+\.[0-9]+(-(alpha|beta|rc)\.[0-9])?(-[0-9a-f]{8})?" | head -1)"
-        ## we have to create tmp dir to untar old tgz, as `tar --skip-old-files` is not supported on all plantforms
-        local tmp_dir
-        tmp_dir="$(mktemp -d -t emqx.XXXXXXX)"
-        $TAR -C "$tmp_dir" -zxf "$tgzfile"
-        mkdir -p "${rel_dir}/releases/"
-        cp -npr "$tmp_dir/releases"/* "${rel_dir}/releases/"
-        ## There is for some reason a copy of the '$PROFILE.rel' file to releases dir,
-        ## the content is duplicated to releases/5.0.0/$PROFILE.rel.
-        ## This file seems to be useless, but yet confusing as it does not change after upgrade/downgrade
-        ## Hence we force delete this file.
-        rm -f "${rel_dir}/releases/${PROFILE}.rel"
-        mkdir -p "${rel_dir}/lib/"
-        cp -npr "$tmp_dir/lib"/* "${rel_dir}/lib/"
-        rm -rf "$tmp_dir"
-        releases+=( "$base_vsn" )
-    done < <("$FIND" _upgrade_base -maxdepth 1 -name "${name_pattern}.tar.gz" -type f)
+    if [ -d "$releases_dir" ]; then
+        while read -r zip; do
+            local base_vsn
+            base_vsn="$(echo "$zip" | grep -oE "[0-9]+\.[0-9]+\.[0-9]+(-[0-9a-f]{8})?")"
+            if [ ! -d "$releases_dir/$base_vsn" ]; then
+                local tmp_dir
+                tmp_dir="$(mktemp -d -t emqx.XXXXXXX)"
+                unzip -q "$zip" "emqx/releases/*" -d "$tmp_dir"
+                unzip -q "$zip" "emqx/lib/*" -d "$tmp_dir"
+                cp -r -n "$tmp_dir/emqx/releases"/* "$releases_dir" || true
+                cp -r -n "$tmp_dir/emqx/lib"/* "$lib_dir" || true
+                rm -rf "$tmp_dir"
+            fi
+            releases+=( "$base_vsn" )
+        done < <(find _upgrade_base -maxdepth 1 -name "*$PROFILE-$SYSTEM*-$ARCH.zip" -type f)
+    fi
     if [ ${#releases[@]} -eq 0 ]; then
         log "No upgrade base found, relup ignored"
         return 0
@@ -199,230 +99,85 @@ cp_dyn_libs() {
     mkdir -p "$target_dir"
     while read -r so_file; do
         cp -L "$so_file" "$target_dir/"
-    done < <("$FIND" "$rel_dir" -type f \( -name "*.so*" -o -name "beam.smp" \) -print0 \
+    done < <(find "$rel_dir" -type f \( -name "*.so*" -o -name "beam.smp" \) -print0 \
         | xargs -0 ldd \
-        | grep -E '(libcrypto)|(libtinfo)|(libatomic)' \
+        | grep -E '(libcrypto)|(libtinfo)' \
         | awk '{print $3}' \
         | sort -u)
 }
 
-## Re-pack the relx assembled .tar.gz to EMQX's package naming scheme
+## make_zip turns .tar.gz into a .zip with a slightly different name.
 ## It assumes the .tar.gz has been built -- relies on Makefile dependency
-make_tgz() {
-    local pkgpath="_packages/${PROFILE}"
-    local src_tarball
-    local target_name
-    local target
+make_zip() {
+    # build the tarball again to ensure relup is included
+    make_rel
 
-    if [ "${IS_ELIXIR:-no}" = "yes" ]
-    then
-      # ensure src_tarball exists
-      ELIXIR_MAKE_TAR=yes make_elixir_rel
-
-      local relpath="_build/${PROFILE}"
-      full_vsn="$(./pkg-vsn.sh "$PROFILE" --long --elixir)"
-    else
-      # build the src_tarball again to ensure relup is included
-      # elixir does not have relup yet.
-      make_rel tar
-
-      local relpath="_build/${PROFILE}/rel/emqx"
-      full_vsn="$(./pkg-vsn.sh "$PROFILE" --long)"
-    fi
-
-    case "$SYSTEM" in
-        macos*)
-            target_name="${PROFILE}-${full_vsn}.zip"
-            ;;
-        windows*)
-            target_name="${PROFILE}-${full_vsn}.zip"
-            ;;
-        *)
-            target_name="${PROFILE}-${full_vsn}.tar.gz"
-            ;;
-    esac
-
-    target="${pkgpath}/${target_name}"
-
-    src_tarball="${relpath}/emqx-${PKG_VSN}.tar.gz"
-    tard="$(mktemp -d -t emqx.XXXXXXX)"
+    tard="/tmp/emqx_untar_${PKG_VSN}"
+    rm -rf "${tard}"
     mkdir -p "${tard}/emqx"
+    local relpath="_build/${PROFILE}/rel/emqx"
+    local pkgpath="_packages/${PROFILE}"
     mkdir -p "${pkgpath}"
-    if [ ! -f "$src_tarball" ]; then
-        log "ERROR: $src_tarball is not found"
+    local tarball="${relpath}/emqx-${PKG_VSN}.tar.gz"
+    if [ ! -f "$tarball" ]; then
+        log "ERROR: $tarball is not found"
     fi
-    $TAR zxf "${src_tarball}" -C "${tard}/emqx"
-    if [ -f "${tard}/emqx/releases/${PKG_VSN}/relup" ]; then
-        ./scripts/relup-build/inject-relup.escript "${tard}/emqx/releases/${PKG_VSN}/relup"
-    fi
-    ## try to be portable for tar.gz packages.
+    local zipball
+    zipball="${pkgpath}/${PROFILE}-${SYSTEM}-${PKG_VSN}-${ARCH}.zip"
+    tar zxf "${tarball}" -C "${tard}/emqx"
+    ## try to be portable for zip packages.
     ## for DEB and RPM packages the dependencies are resoved by yum and apt
     cp_dyn_libs "${tard}/emqx"
-    case "$SYSTEM" in
-        macos*)
-            # if the flag to sign macos binaries is set, but developer certificate
-            # or certificate password is not configured, reset the flag
-            # could happen, for example, when people submit PR from a fork, in this
-            # case they cannot access secrets
-            if [[ "${APPLE_SIGN_BINARIES:-0}" == 1 && \
-                      ( "${APPLE_DEVELOPER_ID_BUNDLE:-0}" == 0 || \
-                           "${APPLE_DEVELOPER_ID_BUNDLE_PASSWORD:-0}" == 0 ) ]]; then
-                echo "Apple developer certificate is not configured, skip signing"
-                APPLE_SIGN_BINARIES=0
-            fi
-            if [ "${APPLE_SIGN_BINARIES:-0}" = 1 ]; then
-                ./scripts/macos-sign-binaries.sh "${tard}/emqx"
-            fi
-            ## create zip after change dir
-            ## to avoid creating an extra level of 'emqx' dir in the .zip file
-            pushd "${tard}/emqx" >/dev/null
-            zip -r "../${target_name}" -- * >/dev/null
-            popd >/dev/null
-            mv "${tard}/${target_name}" "${target}"
-            if [ "${APPLE_SIGN_BINARIES:-0}" = 1 ]; then
-                # notarize the package
-                # if fails, check what went wrong with this command:
-                    # xcrun notarytool log --apple-id <apple id> \
-                    #   --apple-id <apple id> \
-                    #   --password <apple id password>
-                    #   --team-id <apple team id> <submission-id>
-                echo 'Submitting the package for notarization to Apple (normally takes about a minute)'
-                notarytool_output="$(xcrun notarytool submit \
-                                           --apple-id "${APPLE_ID}" \
-                                           --password "${APPLE_ID_PASSWORD}" \
-                                           --team-id "${APPLE_TEAM_ID}" "${target}" \
-                                           --no-progress \
-                                           --wait)"
-                echo "$notarytool_output"
-                echo "$notarytool_output" | grep -q 'status: Accepted' || {
-                    echo 'Notarization failed';
-                    exit 1;
-                }
-            fi
-            # sha256sum may not be available on macos
-            openssl dgst -sha256 "${target}" | cut -d ' ' -f 2  > "${target}.sha256"
-            ;;
-        windows*)
-            pushd "${tard}" >/dev/null
-            7z a "${target_name}" ./emqx/* >/dev/null
-            popd >/dev/null
-            mv "${tard}/${target_name}" "${target}"
-            sha256sum "${target}" | head -c 64 > "${target}.sha256"
-            ;;
-        *)
-            ## create tar after change dir
-            ## to avoid creating an extra level of 'emqx' dir in the .tar.gz file
-            pushd "${tard}/emqx" >/dev/null
-            $TAR -zcf "../${target_name}" -- *
-            popd >/dev/null
-            mv "${tard}/${target_name}" "${target}"
-            sha256sum "${target}" | head -c 64 > "${target}.sha256"
-            ;;
-    esac
-    log "Archive successfully repacked: ${target}"
-    log "Archive sha256sum: $(cat "${target}.sha256")"
+    (cd "${tard}" && zip -qr - emqx) > "${zipball}"
 }
 
-trap docker_cleanup EXIT
-
-docker_cleanup() {
-    rm -f ./.dockerignore >/dev/null
-}
-
-## This function builds the default docker image based on debian 11
+## This function builds the default docker image based on alpine:3.14 (by default)
 make_docker() {
     EMQX_BUILDER="${EMQX_BUILDER:-${EMQX_DEFAULT_BUILDER}}"
     EMQX_RUNNER="${EMQX_RUNNER:-${EMQX_DEFAULT_RUNNER}}"
-    EMQX_DOCKERFILE="${EMQX_DOCKERFILE:-deploy/docker/Dockerfile}"
-    if [[ "$PROFILE" = *-elixir ]]; then
-        PKG_VSN="$PKG_VSN-elixir"
+    if (set -u; : "$GIT_PROXY"); then
+      set -x
+      docker build --no-cache --pull \
+         --build-arg BUILD_FROM="${EMQX_BUILDER}" \
+         --build-arg RUN_FROM="${EMQX_RUNNER}" \
+         --build-arg EMQX_NAME="$PROFILE" \
+         --build-arg PROXY="${GIT_PROXY}" \
+         --tag "emqx/$PROFILE:${PKG_VSN}" \
+         -f "${DOCKERFILE}" .
+    else
+      set -x
+      docker build --no-cache --pull \
+         --build-arg BUILD_FROM="${EMQX_BUILDER}" \
+         --build-arg RUN_FROM="${EMQX_RUNNER}" \
+         --build-arg EMQX_NAME="$PROFILE" \
+         --tag "emqx/$PROFILE:${PKG_VSN}" \
+         -f "${DOCKERFILE}" .
     fi
-    local default_tag="emqx/${PROFILE%%-elixir}:${PKG_VSN}"
-    EMQX_IMAGE_TAG="${EMQX_IMAGE_TAG:-$default_tag}"
-    ## extra_deps is a comma separated list of debian 11 package names
-    local extra_deps=''
-    if [[ "$PROFILE" = *enterprise* ]]; then
-        extra_deps='libsasl2-2'
-    fi
-    echo '_build' >> ./.dockerignore
-    set -x
-    docker build --no-cache --pull \
-       --build-arg BUILD_FROM="${EMQX_BUILDER}" \
-       --build-arg RUN_FROM="${EMQX_RUNNER}" \
-       --build-arg EMQX_NAME="${PROFILE}" \
-       --build-arg EXTRA_DEPS="${extra_deps}" \
-       --tag "${EMQX_IMAGE_TAG}" \
-       -f "${EMQX_DOCKERFILE}" .
-    [[ "${DEBUG:-}" -eq 1 ]] || set +x
-}
-
-function join {
-  local IFS="$1"
-  shift
-  echo "$*"
-}
-
-# used to control the Elixir Mix Release output
-# see docstring in `mix.exs`
-export_elixir_release_vars() {
-  local profile="$1"
-  case "$profile" in
-    emqx|emqx-enterprise)
-      export ELIXIR_MAKE_TAR=${ELIXIR_MAKE_TAR:-no}
-      ;;
-    emqx-pkg|emqx-enterprise-pkg)
-      export ELIXIR_MAKE_TAR=${ELIXIR_MAKE_TAR:-yes}
-      ;;
-    *)
-      echo Invalid profile "$profile"
-      exit 1
-  esac
-  export MIX_ENV="$profile"
 }
 
 log "building artifact=$ARTIFACT for profile=$PROFILE"
 
 case "$ARTIFACT" in
-    apps)
-        just_compile
-        ;;
-    doc|docs)
-        make_docs
-        ;;
     rel)
-        make_rel release
+        make_rel
         ;;
     relup)
         make_relup
         ;;
-    tgz)
-        make_tgz
+    zip)
+        make_zip
         ;;
     pkg)
-        # this only affect build artifacts, such as schema doc
-        export EMQX_ETC_DIR='/etc/emqx/'
         if [ -z "${PKGERDIR:-}" ]; then
             log "Skipped making deb/rpm package for $SYSTEM"
             exit 0
         fi
-        export EMQX_REL_FORM="$PKGERDIR"
-        if [ "${IS_ELIXIR:-}" = 'yes' ]; then
-            make_elixir_rel
-        else
-            make_rel tar
-        fi
-        env EMQX_REL="$(pwd)" \
-            EMQX_BUILD="${PROFILE}" \
-            make -C "deploy/packages/${PKGERDIR}" clean
-        env EMQX_REL="$(pwd)" \
-            EMQX_BUILD="${PROFILE}" \
-            make -C "deploy/packages/${PKGERDIR}"
+        make -C "deploy/packages/${PKGERDIR}" clean
+        EMQX_REL="$(pwd)" EMQX_BUILD="${PROFILE}" SYSTEM="${SYSTEM}" make -C "deploy/packages/${PKGERDIR}"
         ;;
+
     docker)
         make_docker
-        ;;
-    elixir)
-        make_elixir_rel
         ;;
     *)
         log "Unknown artifact $ARTIFACT"
